# Generated by Django 5.0.6 on 2024-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carWashMng", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.DurationField()),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                ("additional_features", models.TextField(blank=True)),
                ("picture", models.FileField(upload_to="carWash/static/uploads")),
            ],
        ),
    ]
