# Generated by Django 5.0.6 on 2024-05-31 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carWashMng", "0003_service_pic_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="pic_path",
        ),
    ]
