# Generated by Django 5.0.6 on 2024-07-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carWashMng", "0004_remove_service_pic_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carWashMng.service",
                    ),
                ),
            ],
        ),
    ]
