# Generated by Django 5.0.6 on 2024-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carWashMng", "0007_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
