# Generated by Django 5.0.6 on 2024-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carWashMng", "0010_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="additional_features",
            field=models.TextField(help_text="Enter features separated by commas."),
        ),
    ]
